### ISSUE TITLE
Neither VTX nor PID scripts working with Taranis Q X7

### ISSUE THREAD

**Issue by vkolotov** [vodka-bears/ersky9x-betaflight-scripts#1]
Hi there, I'm new to `ersky9x` and just installed `ersky9xProvR222d2` version on my Taranis Q X7. Everything works fine, I can bind a kwad, fly it etc. However, neither VTX nor PID script works.

PID script displays zeroes.

VTX script shows "USE A BUTTON" (what does it mean btw?). I tried to push all buttons on the radio. All buttons do nothing except the "Page" button. When I push the "page" button, an empty page is displayed with randomly ordered zeroes.

What hardware has it been tested with? 
Cheers

**Comment by vodka-bears** [comment]
Sorry for long waiting. USE A BUTTON is supposed to indicate that the script hasn't recieved any meaningful data from the FC so you should use a button on your vtx. Randomly ordered zeroes indicate that you should check your SPort configuration. [This](https://openrcforums.com/forum/viewtopic.php?f=7&t=10668&start=30#p140570) might be your case.

**Comment by vodka-bears** [comment]
@vkolotov, tested with 9XR-PRO running r221 and XJT on TX side, XSR-M (FPort), Betaflight MATEKF722 target, AKK FX2 (SmartAudio) on RX side.

**Comment by Phjorttos** [comment]
9XR-Pro running r222d3, tx Frsky R9, rx R9MM (FPort), FC Omni F4SD, vtx Unify HV.

Alert
Script error
Error 103 at line 235
press any key

T9XR-Pro sees telemetry data.

**Comment by vodka-bears** [comment]
@AvaraKaisa, does pid script work?

**Comment by Phjorttos** [comment]
pid script start but shows only zeros.

**Comment by vodka-bears** [comment]
@AvaraKaisa, when does vtx script crash? On start or on save? If on save does it indicate current vtx settings?

**Comment by Phjorttos** [comment]
Vtx script won't even start. It just gives the error message.

**Comment by vodka-bears** [comment]
@AvaraKaisa, well, I don't even know how to fix this. I don't have r9 hardware. Try this maybe. https://github.com/midelic/Ersky9x-Tx-bas-scripts/blob/master/src/BF_basic_VTX_1.0.bas

**Comment by Phjorttos** [comment]
Tried Midelics script earlier and it starts but show only zeros.

**Comment by vodka-bears** [comment]
@AvaraKaisa, I'll ask my friend to test the scripts with R9, but I can't guarantee anything.

P.S. midelic just used some of my vtx related code when he made a vtx script as well as I used his SPort related code.

P.P.S. His script  anyway wouldn't work with your config because one of FPort packets differs in one byte with SPort and he didn't make some little edit.

**Comment by Phjorttos** [comment]
Latest vb_ersky test version & updated script are now working nicely.
